# app.yaml - Configuration for Google App Engine
runtime: nodejs18
service: ai

env_variables:
  GOOGLE_CLIENT_ID: ""

handlers:
  - url: /api/.*
    script: auto
    secure: always

  - url: /static
    static_dir: public/static
    secure: always

  - url: /(.*\.(json|ico|js|css|png|jpg|gif|svg|woff|woff2|ttf|eot))$
    static_files: public/\1
    upload: public/.*\.(json|ico|js|css|png|jpg|gif|svg|woff|woff2|ttf|eot)$
    secure: always

  - url: /.*
    script: auto
    secure: always
